### ISSUE TITLE
[UI]:Spilling of the page on the right side

### ISSUE THREAD

**Issue by St80ene** [layer5io/service-mesh-performance#120] opened 2020-09-07 13:55 UTC
**Description**

Not fully responsive on mobile devices
Menu button not fully contained in the navbar on mobile device viewport
**Expected Behavior**

White space observed at the right side of the screen while scrolling on Mobile devices
Menu button on the navbar should adjust properly according to device viewport
**Screenshots**

(https://user-images.githubusercontent.com/51080127/92394228-08a92280-f119-11ea-9092-217a6ca9d59b.jpg)
(https://user-images.githubusercontent.com/51080127/92394245-12328a80-f119-11ea-8b72-4af5a4f5f2ea.jpg)

**Environment:**
 - OS: [e.g. Ubuntu]
 - Browser: [e.g. Chrome, Safari]
Chrome
 - Version: [e.g. 22]
Version 83.0.4103.97 (Official Build) (64-bit)
 - Device: [e.g. laptop, iPhone 8]
Mobile phones
---
[Optional] **To Reproduce**

**Comment by Nikhil-Ladha** [comment] 2020-09-07 14:01
Thank you @St80ene for opening this issue. Would you like to tackle this one?

**Comment by St80ene** [comment] 2020-09-07 14:11
I would had loved to but I have very little or zero knowledge of the technologies used on the project. Thanks.

**Comment by Nikhil-Ladha** [comment] 2020-09-07 15:46
> I would had loved to but I have very little or zero knowledge of the technologies used on the project. Thanks.

Okay, no sweat 👍🏼.

**Comment by Nikhil-Ladha** [comment] 2020-09-07 15:47
@Neilblaze or @JubayerJoy this is something you guys might knock of first!

**Comment by JubayerJoy** [comment] 2020-09-07 18:04
Nice catch @St80ene 🚀
@Nikhil-Ladha, this looks like an urgent fix, I've checked on my phones, looks horrible.
Regrettably, I'm preoccupied with an academic project this week, if not fixed by 15 Sept, I'll have a go on this.
Good luck!

**Comment by Favalcodes** [comment] 2020-09-11 16:25
Can I take this?

**Comment by Ruth-ikegah** [comment] 2020-09-11 16:27
Sure go ahead @Favalcodes

**Comment by Favalcodes** [comment] 2020-09-11 16:29
Alright, thanks

**Comment by Favalcodes** [comment] 2020-09-24 21:52
Sorry, I couldn't sort this issue out, My system has an issue as of now, Please can this issue be assigned to someone else, sorry for the inconveniencies.

**Comment by leecalcote** [comment] 2020-09-25 02:00
No problem, @Favalcodes. Completely understood. 👌

**Comment by JubayerJoy** [comment] 2020-09-25 02:21
I'll try to solve this. Should be an easy fix. 🤞

**Comment by leecalcote** [comment] 2020-09-25 10:16
Thank you @JubayerJoy

**Comment by JubayerJoy** [comment] 2020-09-28 17:36
**Update:** I have found the cause of this error. Working on it. 👍

**Closed** 2020-09-30 18:42 UTC
Labels: hacktoberfest, kind/bug, language/html, priority/high
